#! /bin/sh
### BEGIN INIT INFO
# Provides:          killasplashscreen
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: killasplashscreen
# Description:       Stop showing custom splashscreen
### END INIT INFO

do_start () {

    /usr/bin/killall fbi 2> /dev/null
    exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: killasplashscreen [start|stop]" >&2
    exit 3
    ;;
esac

:

