#!/bin/sh
### BEGIN INIT INFO
# Provides:          asplashscreen
# Required-Start:
# Required-Stop:
# Default-Start:     S 1
# Default-Stop:
# Short-Description: asplashscreen
# Description:       Show custom splashscreen
### END INIT INFO

do_start () {
	/usr/bin/fbi -T 1 -noverbose /usr/share/images/tf-image.png &> /dev/null
    exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: asplashscreen [start|stop]" >&2
    exit 3
    ;;
esac

:
