#!/usr/bin/env bash

zenity \
--question \
--title="System Reboot" \
--text "Are you sure you want to reboot the system ?" \
--ok-label="Yes" \
--cancel-label="No"

if [ $? = 0 ]; then
	/sbin/reboot
fi
